### ISSUE TITLE
What is the part number of the microsd slot holder?

### ISSUE THREAD

**Issue by VersatileNinja** [martinx72/MX4SIO-RGR#1]
Can you kindly advise the part number and where I could source it online? Thanks!

**Comment by martinx72** [comment]
You may try digikey.com

And parts number is already on the BOM list. Please just search over the website.

**Comment by VersatileNinja** [comment]
> You may try digikey.com
> 
> And parts number is already on the BOM list. Please just search over the website.

The part number on the website in the BOM lists it as "MICROSD_PP", which is not a digi key part number for example. I just want to make sure I get the right part number from digi key or any other supplier, unless they are all universal.

**Comment by martinx72** [comment]
> > You may try digikey.com
> 
> > 
> 
> > And parts number is already on the BOM list. Please just search over the website.
> 
> 
> 
> The part number on the website in the BOM lists it as "MICROSD_PP", which is not a digi key part number for example. I just want to make sure I get the right part number from digi key or any other supplier, unless they are all universal.

Try TFP09-2-12B / CSD11251278002
Forgot to push the last local commit and this parts is also use on my other design for NEOGEO CD SD Loader TF Adaptor in other repo.
